### ISSUE TITLE
Call to undefined function ProcessWire\setting()

### ISSUE THREAD

**Issue by matjazpotocnik** [MetaTunes/FieldtypeMeasurement#2]
in ...\wwwroot\site\modules\FieldtypeMeasurement\Measurement.php:598

**Comment by MetaTunes** [comment]
That should be available in 3.0.119+ provided you have set $config->useFunctionsAPI = true;

**Comment by matjazpotocnik** [comment]
You are right. I didn't have this turned on. Maybe worth checking upon module installation?

**Comment by matjazpotocnik** [comment]
Now I'm getting "Measurement: Bad API return (maybe excess calls?)" and conversion between currency units fails, emptying the magnitude value.

**Comment by MetaTunes** [comment]
I’ve never had that error. Do you have TracyDebugger? Can you supply any more details? What was the context?

**Comment by matjazpotocnik** [comment]
"Get your API key from https://www.alphavantage.co/ and put it in your config file" explains everything. There is a mention of this in manuals but nothing specific on how and where to put the key. Perhaps it would be better to use the default return value of `'Error Message' => 'the parameter apikey is invalid or missing. Please claim your free API key on (https://www.alphavantage.co/support/#api-key). It should take less than 20 seconds.'`

**Comment by matjazpotocnik** [comment]
Now I have a key, but get this error in Currency.php:

array_merge_recursive(): Argument #1 must be of type array, null given
$newVar = array_merge_recursive($sessionVar, [$currency_from => [$currency_to => ['time' => time(), 'rate' => $rate]]]);

$sessionVar is null.

**Comment by MetaTunes** [comment]
I haven't used the Currency feature in a while. I'll look into it.

**Comment by MetaTunes** [comment]
Quick code fix. Replace line 14 in Currency.php with $sessionVar = (wire()->session->get('MeasurementCurrency')) ?: [];
I'll do a new module version in due course.

**Comment by matjazpotocnik** [comment]
Thanks, I already fixed it in a similar way locally, so I didn't reopen the issue.
